# Generated by Django 3.1.7 on 2021-02-23 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncompletedorder',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 17, 57, 6, 760604, tzinfo=utc)),
        ),
    ]
