# Generated by Django 3.1.7 on 2021-03-04 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210224_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='amount_to_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 17, 56, 12, 78226, tzinfo=utc)),
        ),
    ]
